### PR TITLE
Update to Clojurescript 0.0-2727

### PR DESCRIPTION
**Pull request by martinklepsch**
I tested this with [this sample project](https://github.com/martinklepsch/testbed) so far probably should be tested with boot-cljs-example as well (I can do that).

Besides that it'd be nice if some people could give it a spin, Om already utilises the `foreign-libs` stuff so if anyone has some Om app, I think that'd be a good test case. /cc @Deraen @pandeiro

Thanks

**PS.** I can squash the commits before merging if that's desired.

### CODE REVIEW

**Comment by martinklepsch** [comment]
One thing that should also be tested is if `cljs-repl` & `reload` tasks still work as expected.
There were some people on the Clojurescript ML that reported issues with cljs 2727

**Comment by pandeiro** [comment]
@martinklepsch Looking at the 2727 branch, it seems like it's still pulling in [org.clojure/clojurescript "0.0-2629 :scope "test"] - am I missing something?

**Comment by martinklepsch** [comment]
@pandeiro good point. I think 2727 is used [in a pod](https://github.com/martinklepsch/boot-cljs/commit/f504779674bb6b2d8c89eba50f915a1bb0d6dc4e) but this should be changed in build.boot as well, thanks.

**Comment by pandeiro** [comment]
ah ok @martinklepsch, i guess just for clarity's sake yeah?

**Comment by pandeiro** [comment]
@martinklepsch My current project's building successfully with this new version :+1:

**Comment by martinklepsch** [comment]
Updated the version numbers in `build.boot`.

**Pull request merged**
